stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean install
- name: Test
  steps:
  - runScriptConfig:
      image: katalonstudio/katalon
      shellScript: katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15
        -projectPath="/tmp/katalon_execute/project" -testSuitePath="Test Suites/TS_RegressionTest"
    when:
      branch:
        include:
        - '!master'
  when:
    branch:
      exclude:
      - '!master'
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34366
    when:
      branch:
        include:
        - '!master'
  when:
    branch:
      include:
      - '!master'
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - '!master'
