stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean install
- name: Test
  steps:
  - runScriptConfig:
      image: katalonstudio/katalon
      shellScript: katalon -noSplash -email="your-email" -password="your-password" -runMode=console -consoleLog -projectPath="/directory-of-your-project/your-project.prj" -retry=0 -testSuitePath="Test Suites/your-test-suite" -browserType="Chrome"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
