stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: mvn clean install
- name: Test
  steps:
  - runScriptConfig:
      image: katalonstudio/katalon
      shellScript: mkdir -p /tmp/katalon_execute/ && touch /tmp/katalon_execute/project
        && katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test
        Suites/TS_RegressionTest"
  when:
    branch:
      exclude:
      - '!master'
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
