/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetproductfromuseridResponse implements Serializable {


    @ColumnAlias("product")
    private String product;

    public String getProduct() {
        return this.product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetproductfromuseridResponse)) return false;
        final GetproductfromuseridResponse getproductfromuseridResponse = (GetproductfromuseridResponse) o;
        return Objects.equals(getProduct(), getproductfromuseridResponse.getProduct());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProduct());
    }
}