/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Top5usersMoreOppoResponse implements Serializable {


    @ColumnAlias("totoppo")
    private Long totoppo;

    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    public Long getTotoppo() {
        return this.totoppo;
    }

    public void setTotoppo(Long totoppo) {
        this.totoppo = totoppo;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Top5usersMoreOppoResponse)) return false;
        final Top5usersMoreOppoResponse top5usersMoreOppoResponse = (Top5usersMoreOppoResponse) o;
        return Objects.equals(getTotoppo(), top5usersMoreOppoResponse.getTotoppo()) &&
                Objects.equals(getFirstname(), top5usersMoreOppoResponse.getFirstname()) &&
                Objects.equals(getLastname(), top5usersMoreOppoResponse.getLastname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotoppo(),
                getFirstname(),
                getLastname());
    }
}