/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TotalhwswVsDeltaResponse implements Serializable {


    @ColumnAlias("totsum")
    private BigInteger totsum;

    @ColumnAlias("NAME")
    private String name;

    public BigInteger getTotsum() {
        return this.totsum;
    }

    public void setTotsum(BigInteger totsum) {
        this.totsum = totsum;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TotalhwswVsDeltaResponse)) return false;
        final TotalhwswVsDeltaResponse totalhwswVsDeltaResponse = (TotalhwswVsDeltaResponse) o;
        return Objects.equals(getTotsum(), totalhwswVsDeltaResponse.getTotsum()) &&
                Objects.equals(getName(), totalhwswVsDeltaResponse.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotsum(),
                getName());
    }
}