/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TotalProductCategoriesResponse implements Serializable {


    @ColumnAlias("tot")
    private Long tot;

    @ColumnAlias("name")
    private String name;

    public Long getTot() {
        return this.tot;
    }

    public void setTot(Long tot) {
        this.tot = tot;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TotalProductCategoriesResponse)) return false;
        final TotalProductCategoriesResponse totalProductCategoriesResponse = (TotalProductCategoriesResponse) o;
        return Objects.equals(getTot(), totalProductCategoriesResponse.getTot()) &&
                Objects.equals(getName(), totalProductCategoriesResponse.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTot(),
                getName());
    }
}