/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TotdeltaResponse implements Serializable {


    @ColumnAlias("totdelta")
    private BigInteger totdelta;

    public BigInteger getTotdelta() {
        return this.totdelta;
    }

    public void setTotdelta(BigInteger totdelta) {
        this.totdelta = totdelta;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TotdeltaResponse)) return false;
        final TotdeltaResponse totdeltaResponse = (TotdeltaResponse) o;
        return Objects.equals(getTotdelta(), totdeltaResponse.getTotdelta());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotdelta());
    }
}