/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Userthathasoppo2Response implements Serializable {


    @ColumnAlias("completename")
    private String completename;

    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("Total_Bid_Amount")
    private BigDecimal totalBidAmount;

    public String getCompletename() {
        return this.completename;
    }

    public void setCompletename(String completename) {
        this.completename = completename;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public BigDecimal getTotalBidAmount() {
        return this.totalBidAmount;
    }

    public void setTotalBidAmount(BigDecimal totalBidAmount) {
        this.totalBidAmount = totalBidAmount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Userthathasoppo2Response)) return false;
        final Userthathasoppo2Response userthathasoppo2response = (Userthathasoppo2Response) o;
        return Objects.equals(getCompletename(), userthathasoppo2response.getCompletename()) &&
                Objects.equals(getId(), userthathasoppo2response.getId()) &&
                Objects.equals(getTotalBidAmount(), userthathasoppo2response.getTotalBidAmount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCompletename(),
                getId(),
                getTotalBidAmount());
    }
}