/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UsersSumOpportunityTotalResponse implements Serializable {


    @ColumnAlias("fullname")
    private String fullname;

    @ColumnAlias("totvalue")
    private BigInteger totvalue;

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public BigInteger getTotvalue() {
        return this.totvalue;
    }

    public void setTotvalue(BigInteger totvalue) {
        this.totvalue = totvalue;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UsersSumOpportunityTotalResponse)) return false;
        final UsersSumOpportunityTotalResponse usersSumOpportunityTotalResponse = (UsersSumOpportunityTotalResponse) o;
        return Objects.equals(getFullname(), usersSumOpportunityTotalResponse.getFullname()) &&
                Objects.equals(getTotvalue(), usersSumOpportunityTotalResponse.getTotvalue());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFullname(),
                getTotvalue());
    }
}