/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class WonvstargetResponse implements Serializable {


    @ColumnAlias("totwon")
    private BigInteger totwon;

    @ColumnAlias("target")
    private String target;

    @ColumnAlias("username")
    private String username;

    public BigInteger getTotwon() {
        return this.totwon;
    }

    public void setTotwon(BigInteger totwon) {
        this.totwon = totwon;
    }

    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof WonvstargetResponse)) return false;
        final WonvstargetResponse wonvstargetResponse = (WonvstargetResponse) o;
        return Objects.equals(getTotwon(), wonvstargetResponse.getTotwon()) &&
                Objects.equals(getTarget(), wonvstargetResponse.getTarget()) &&
                Objects.equals(getUsername(), wonvstargetResponse.getUsername());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTotwon(),
                getTarget(),
                getUsername());
    }
}