/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.crmweb.crm.Categories;
import com.crmweb.crm.Opportunities;
import com.crmweb.crm.Projects;
import com.crmweb.crm.Tasks;

/**
 * Service object for domain model class {@link Categories}.
 */
public interface CategoriesService {

    /**
     * Creates a new Categories. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Categories if any.
     *
     * @param categories Details of the Categories to be created; value cannot be null.
     * @return The newly created Categories.
     */
    Categories create(@Valid Categories categories);


	/**
     * Returns Categories by given id if exists.
     *
     * @param categoriesId The id of the Categories to get; value cannot be null.
     * @return Categories associated with the given categoriesId.
	 * @throws EntityNotFoundException If no Categories is found.
     */
    Categories getById(Integer categoriesId);

    /**
     * Find and return the Categories by given id if exists, returns null otherwise.
     *
     * @param categoriesId The id of the Categories to get; value cannot be null.
     * @return Categories associated with the given categoriesId.
     */
    Categories findById(Integer categoriesId);

	/**
     * Find and return the list of Categories by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param categoriesIds The id's of the Categories to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Categories associated with the given categoriesIds.
     */
    List<Categories> findByMultipleIds(List<Integer> categoriesIds, boolean orderedReturn);


    /**
     * Updates the details of an existing Categories. It replaces all fields of the existing Categories with the given categories.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Categories if any.
     *
     * @param categories The details of the Categories to be updated; value cannot be null.
     * @return The updated Categories.
     * @throws EntityNotFoundException if no Categories is found with given input.
     */
    Categories update(@Valid Categories categories);

    /**
     * Deletes an existing Categories with the given id.
     *
     * @param categoriesId The id of the Categories to be deleted; value cannot be null.
     * @return The deleted Categories.
     * @throws EntityNotFoundException if no Categories found with the given id.
     */
    Categories delete(Integer categoriesId);

    /**
     * Deletes an existing Categories with the given object.
     *
     * @param categories The instance of the Categories to be deleted; value cannot be null.
     */
    void delete(Categories categories);

    /**
     * Find all Categories matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Categories.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Categories> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Categories matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Categories.
     *
     * @see Pageable
     * @see Page
     */
    Page<Categories> findAll(String query, Pageable pageable);

    /**
     * Exports all Categories matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Categories matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Categories in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Categories.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);

    /*
     * Returns the associated opportunitieses for given Categories id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Opportunities instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Opportunities> findAssociatedOpportunitieses(Integer id, Pageable pageable);

    /*
     * Returns the associated projectses for given Categories id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Projects instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Projects> findAssociatedProjectses(Integer id, Pageable pageable);

    /*
     * Returns the associated taskses for given Categories id.
     *
     * @param id value of id; value cannot be null
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of associated Tasks instances.
     *
     * @see Pageable
     * @see Page
     */
    Page<Tasks> findAssociatedTaskses(Integer id, Pageable pageable);

}