/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.crmweb.crm.models.query.*;

@Service
public class CrmQueryExecutorServiceImpl implements CrmQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(CrmQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("crmWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<WonvstargetResponse> executeWonvstarget(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("wonvstarget", params, WonvstargetResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportWonvstarget(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("wonvstarget", params, WonvstargetResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<TotdeltaResponse> executeTotdelta(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("totdelta", params, TotdeltaResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTotdelta(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("totdelta", params, TotdeltaResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<TotcommitResponse> executeTotcommit(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("totcommit", params, TotcommitResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTotcommit(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("totcommit", params, TotcommitResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<GetproductfromuseridResponse> executeGetproductfromuserid(String iduser, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("iduser", iduser);

        return queryExecutor.executeNamedQuery("getproductfromuserid", params, GetproductfromuseridResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportGetproductfromuserid(String iduser, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("iduser", iduser);

        QueryProcedureInput queryInput = new QueryProcedureInput("getproductfromuserid", params, GetproductfromuseridResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<Top5valopposResponse> executeTop5valoppos(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("top5valoppos", params, Top5valopposResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTop5valoppos(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("top5valoppos", params, Top5valopposResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<UserthathasOpenOpportunitiesResponse> executeUserthathasOpenOpportunities(String date1, String date2, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("date1", date1);
        params.put("date2", date2);

        return queryExecutor.executeNamedQuery("userthathasOpenOpportunities", params, UserthathasOpenOpportunitiesResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportUserthathasOpenOpportunities(String date1, String date2, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("date1", date1);
        params.put("date2", date2);

        QueryProcedureInput queryInput = new QueryProcedureInput("userthathasOpenOpportunities", params, UserthathasOpenOpportunitiesResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<ProjectcountusersandproductsResponse> executeProjectcountusersandproducts(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("projectcountusersandproducts", params, ProjectcountusersandproductsResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportProjectcountusersandproducts(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("projectcountusersandproducts", params, ProjectcountusersandproductsResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<TotsumUpsideResponse> executeTotsumUpside(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("totsumUpside", params, TotsumUpsideResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTotsumUpside(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("totsumUpside", params, TotsumUpsideResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<UsersSumOpportunityTotalResponse> executeUsers_sum_opportunity_total(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("users_sum_opportunity_total", params, UsersSumOpportunityTotalResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportUsers_sum_opportunity_total(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("users_sum_opportunity_total", params, UsersSumOpportunityTotalResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<TotsumoppoResponse> executeTotsumoppo(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("totsumoppo", params, TotsumoppoResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTotsumoppo(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("totsumoppo", params, TotsumoppoResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<Top5usersMoreOppoResponse> executeTop5usersMoreOppo(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("top5usersMoreOppo", params, Top5usersMoreOppoResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTop5usersMoreOppo(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("top5usersMoreOppo", params, Top5usersMoreOppoResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<TotalhwswVsDeltaResponse> executeTotalhwsw_vs_delta(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("totalhwsw_vs_delta", params, TotalhwswVsDeltaResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTotalhwsw_vs_delta(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("totalhwsw_vs_delta", params, TotalhwswVsDeltaResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<TotalProductCategoriesResponse> executeTotal_product_categories(Pageable pageable) {
        Map<String, Object> params = new HashMap<>(0);


        return queryExecutor.executeNamedQuery("total_product_categories", params, TotalProductCategoriesResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportTotal_product_categories(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(0);


        QueryProcedureInput queryInput = new QueryProcedureInput("total_product_categories", params, TotalProductCategoriesResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<SearchprojectopportunitiesResponse> executeSearchprojectopportunities(String words, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("words", words);

        return queryExecutor.executeNamedQuery("searchprojectopportunities", params, SearchprojectopportunitiesResponse.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportSearchprojectopportunities(String words, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("words", words);

        QueryProcedureInput queryInput = new QueryProcedureInput("searchprojectopportunities", params, SearchprojectopportunitiesResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "crmTransactionManager", readOnly = true)
    @Override
    public Page<Userthathasoppo2Response> executeUserthathasoppo2(String date1, String date2, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("date1", date1);
        params.put("date2", date2);

        return queryExecutor.executeNamedQuery("userthathasoppo2", params, Userthathasoppo2Response.class, pageable);
    }

    @Transactional(value = "crmTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportUserthathasoppo2(String date1, String date2, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("date1", date1);
        params.put("date2", date2);

        QueryProcedureInput queryInput = new QueryProcedureInput("userthathasoppo2", params, Userthathasoppo2Response.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}