/*Copyright (c) 2018-2019 deltadatamandiri.com All Rights Reserved.
 This software is the confidential and proprietary information of deltadatamandiri.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with deltadatamandiri.com*/
package com.crmweb.crm.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.crmweb.crm.Departments;
import com.crmweb.crm.Locations;
import com.crmweb.crm.Posts;


/**
 * ServiceImpl object for domain model class Locations.
 *
 * @see Locations
 */
@Service("crm.LocationsService")
@Validated
public class LocationsServiceImpl implements LocationsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(LocationsServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("crm.DepartmentsService")
    private DepartmentsService departmentsService;

    @Lazy
    @Autowired
    @Qualifier("crm.PostsService")
    private PostsService postsService;

    @Autowired
    @Qualifier("crm.LocationsDao")
    private WMGenericDao<Locations, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Locations, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "crmTransactionManager")
    @Override
    public Locations create(Locations locations) {
        LOGGER.debug("Creating a new Locations with information: {}", locations);

        Locations locationsCreated = this.wmGenericDao.create(locations);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(locationsCreated);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Locations getById(Integer locationsId) {
        LOGGER.debug("Finding Locations by id: {}", locationsId);
        return this.wmGenericDao.findById(locationsId);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Locations findById(Integer locationsId) {
        LOGGER.debug("Finding Locations by id: {}", locationsId);
        try {
            return this.wmGenericDao.findById(locationsId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Locations found with id: {}", locationsId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public List<Locations> findByMultipleIds(List<Integer> locationsIds, boolean orderedReturn) {
        LOGGER.debug("Finding Locations by ids: {}", locationsIds);

        return this.wmGenericDao.findByMultipleIds(locationsIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "crmTransactionManager")
    @Override
    public Locations update(Locations locations) {
        LOGGER.debug("Updating Locations with information: {}", locations);

        this.wmGenericDao.update(locations);
        this.wmGenericDao.refresh(locations);

        return locations;
    }

    @Transactional(value = "crmTransactionManager")
    @Override
    public Locations delete(Integer locationsId) {
        LOGGER.debug("Deleting Locations with id: {}", locationsId);
        Locations deleted = this.wmGenericDao.findById(locationsId);
        if (deleted == null) {
            LOGGER.debug("No Locations found with id: {}", locationsId);
            throw new EntityNotFoundException(String.valueOf(locationsId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "crmTransactionManager")
    @Override
    public void delete(Locations locations) {
        LOGGER.debug("Deleting Locations with {}", locations);
        this.wmGenericDao.delete(locations);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Page<Locations> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Locations");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Page<Locations> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Locations");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service crm for table Locations to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service crm for table Locations to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Page<Departments> findAssociatedDepartmentses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated departmentses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("locations.id = '" + id + "'");

        return departmentsService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "crmTransactionManager")
    @Override
    public Page<Posts> findAssociatedPostses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated postses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("locations.id = '" + id + "'");

        return postsService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service DepartmentsService instance
     */
    protected void setDepartmentsService(DepartmentsService service) {
        this.departmentsService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service PostsService instance
     */
    protected void setPostsService(PostsService service) {
        this.postsService = service;
    }

}